In [1]:
import os
import shutil
import pandas as pd


csv_file = 'Train.csv'  
images_folder = 'train'  
output_folder = 'Dataset' 


df = pd.read_csv(csv_file)


for label in range(5):  
    os.makedirs(os.path.join(output_folder, str(label)), exist_ok=True)


for _, row in df.iterrows():
    filename = row['filename']
    label = row['label']
    
   
    src_path = os.path.join(images_folder, filename)
    if os.path.exists(src_path):
      
        dest_folder = os.path.join(output_folder, str(label))
        dest_path = os.path.join(dest_folder, filename)
        
       
        shutil.move(src_path, dest_path)
        print(f"Moved {filename} to {dest_folder}")
    else:
        print(f"Warning: {filename} not found in the images folder!")

print("Image organization complete!")


Moved Image_1.jpg to Dataset\0
Moved Image_2.jpg to Dataset\1
Moved Image_3.jpg to Dataset\0
Moved Image_4.jpg to Dataset\1
Moved Image_5.jpg to Dataset\2
Moved Image_6.jpg to Dataset\2
Moved Image_7.jpg to Dataset\1
Moved Image_8.jpg to Dataset\0
Moved Image_9.jpg to Dataset\2
Moved Image_10.jpg to Dataset\0
Moved Image_11.jpg to Dataset\2
Moved Image_12.jpg to Dataset\1
Moved Image_13.jpg to Dataset\0
Moved Image_14.jpg to Dataset\4
Moved Image_15.jpg to Dataset\1
Moved Image_16.jpg to Dataset\0
Moved Image_17.jpg to Dataset\3
Moved Image_18.jpg to Dataset\2
Moved Image_19.jpg to Dataset\0
Moved Image_20.jpg to Dataset\2
Moved Image_21.jpg to Dataset\2
Moved Image_22.jpg to Dataset\1
Moved Image_23.jpg to Dataset\4
Moved Image_24.jpg to Dataset\2
Moved Image_25.jpg to Dataset\0
Moved Image_26.jpg to Dataset\0
Moved Image_27.jpg to Dataset\2
Moved Image_28.jpg to Dataset\3
Moved Image_29.jpg to Dataset\0
Moved Image_30.jpg to Dataset\0
Moved Image_31.jpg to Dataset\2
Moved Image_32.jp

In [6]:
import torch
import torch.nn as nn
import torch.optim as optim
from torchvision import datasets, transforms, models
from torch.utils.data import DataLoader
import os
from tqdm import tqdm 


train_dir = 'Dataset' 


transform = transforms.Compose([
    transforms.Resize((224, 224)),  
    transforms.ToTensor(),  
    transforms.Normalize(mean=[0.485, 0.456, 0.406], std=[0.229, 0.224, 0.225])  
])


train_dataset = datasets.ImageFolder(train_dir, transform=transform)
train_loader = DataLoader(train_dataset, batch_size=32, shuffle=True)


model = models.resnet18(pretrained=False)


pretrained_model_path = 'resnet18-f37072fd.pth'  
model.load_state_dict(torch.load(pretrained_model_path, weights_only=True))


model.fc = nn.Linear(model.fc.in_features, 5)  


device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
model = model.to(device)


criterion = nn.CrossEntropyLoss()
optimizer = optim.Adam(model.parameters(), lr=0.001)


num_epochs = 10  
for epoch in range(num_epochs):
    model.train()  
    running_loss = 0.0
    correct_predictions = 0
    total_predictions = 0
    
   
    with tqdm(train_loader, unit="batch", desc=f"Epoch {epoch+1}/{num_epochs}") as tepoch:
        for inputs, labels in tepoch:
            inputs, labels = inputs.to(device), labels.to(device)
            
            
            optimizer.zero_grad()
            
           
            outputs = model(inputs)
            loss = criterion(outputs, labels)
            
           
            loss.backward()
            optimizer.step()
            
           
            running_loss += loss.item()
            _, predicted = torch.max(outputs, 1)
            correct_predictions += (predicted == labels).sum().item()
            total_predictions += labels.size(0)
            
            
            tepoch.set_postfix(loss=running_loss / (tepoch.n + 1), accuracy=100 * correct_predictions / total_predictions)
    
    epoch_loss = running_loss / len(train_loader)
    epoch_accuracy = 100 * correct_predictions / total_predictions
    print(f"Epoch [{epoch + 1}/{num_epochs}], Loss: {epoch_loss:.4f}, Accuracy: {epoch_accuracy:.2f}%")


torch.save(model.state_dict(), 'knee_xray_model.pth')
print("Model training complete and saved as 'knee_xray_model.pth'.")


Epoch 1/10: 100%|███████████████████████████████████████| 245/245 [09:46<00:00,  2.39s/batch, accuracy=52.2, loss=1.14]


Epoch [1/10], Loss: 1.1424, Accuracy: 52.18%


Epoch 2/10: 100%|████████████████████████████████████████| 245/245 [09:42<00:00,  2.38s/batch, accuracy=62, loss=0.904]


Epoch [2/10], Loss: 0.9039, Accuracy: 62.05%


Epoch 3/10: 100%|██████████████████████████████████████| 245/245 [09:34<00:00,  2.35s/batch, accuracy=64.1, loss=0.848]


Epoch [3/10], Loss: 0.8479, Accuracy: 64.13%


Epoch 4/10: 100%|██████████████████████████████████████| 245/245 [09:37<00:00,  2.36s/batch, accuracy=67.2, loss=0.792]


Epoch [4/10], Loss: 0.7924, Accuracy: 67.17%


Epoch 5/10: 100%|██████████████████████████████████████| 245/245 [09:41<00:00,  2.37s/batch, accuracy=68.3, loss=0.742]


Epoch [5/10], Loss: 0.7416, Accuracy: 68.28%


Epoch 6/10: 100%|███████████████████████████████████████| 245/245 [09:38<00:00,  2.36s/batch, accuracy=71.2, loss=0.69]


Epoch [6/10], Loss: 0.6899, Accuracy: 71.22%


Epoch 7/10: 100%|██████████████████████████████████████| 245/245 [09:37<00:00,  2.36s/batch, accuracy=73.9, loss=0.623]


Epoch [7/10], Loss: 0.6226, Accuracy: 73.94%


Epoch 8/10: 100%|██████████████████████████████████████| 245/245 [09:36<00:00,  2.35s/batch, accuracy=76.7, loss=0.553]


Epoch [8/10], Loss: 0.5535, Accuracy: 76.67%


Epoch 9/10: 100%|████████████████████████████████████████| 245/245 [10:17<00:00,  2.52s/batch, accuracy=81, loss=0.462]


Epoch [9/10], Loss: 0.4621, Accuracy: 80.98%


Epoch 10/10: 100%|██████████████████████████████████████| 245/245 [12:05<00:00,  2.96s/batch, accuracy=84.5, loss=0.39]

Epoch [10/10], Loss: 0.3904, Accuracy: 84.50%
Model training complete and saved as 'knee_xray_model.pth'.


In [8]:
import os
import torch
import torch.nn as nn
import pandas as pd
from torchvision import transforms, models
from PIL import Image
from sklearn.metrics import accuracy_score, confusion_matrix
from natsort import natsorted
from tqdm import tqdm  


device = torch.device("cuda" if torch.cuda.is_available() else "cpu")


model = models.resnet18(pretrained=False)
model.fc = nn.Linear(model.fc.in_features, 5) 
model.load_state_dict(torch.load('knee_xray_model.pth', map_location=device, weights_only=True))
model.to(device)
model.eval()


transform = transforms.Compose([
    transforms.Resize((224, 224)),  
    transforms.ToTensor(),  
    transforms.Normalize(mean=[0.485, 0.456, 0.406], std=[0.229, 0.224, 0.225])  
])


test_csv = "Testing.CSV"
test_images = pd.read_csv(test_csv, header=None, names=["filename"])


train_csv = "train.csv"
train_data = pd.read_csv(train_csv, header=None, names=["filename", "label"])
actual_labels_dict = dict(zip(train_data["filename"], train_data["label"]))


test_folder = "testing"


actual_filenames = natsorted(os.listdir(test_folder))


missing_files = [file for file in test_images["filename"] if file not in actual_filenames]
if missing_files:
    print("\nMissing Files from 'test' Folder:")
    print(missing_files)
else:
    print("\nAll files from 'Test.CSV' are present in the 'test' folder.")


predictions, actual_labels, filenames = [], [], []


for filename in tqdm(test_images["filename"], desc="Processing images", unit="image"):
    image_path = os.path.join(test_folder, filename)
    if filename not in actual_filenames:
        continue  

   
    image = Image.open(image_path)
    image = transform(image).unsqueeze(0).to(device)

   
    with torch.no_grad():
        outputs = model(image)
        _, predicted_label = torch.max(outputs, 1)
        predictions.append(predicted_label.item())

    
    actual_label = actual_labels_dict.get(filename)
    if actual_label is not None:
        actual_labels.append(actual_label)
        filenames.append(filename)


actual_labels = [int(label) if isinstance(label, str) else label for label in actual_labels]
predictions = [int(pred) if isinstance(pred, str) else pred for pred in predictions]


accuracy = accuracy_score(actual_labels, predictions)
print(f"\nModel Accuracy: {accuracy * 100:.2f}%")


conf_matrix = confusion_matrix(actual_labels, predictions)
print("\nConfusion Matrix:")
print(conf_matrix)


results_df = pd.DataFrame({"filename": filenames, "actual_label": actual_labels, "predicted_label": predictions})
results_df.to_csv("predictions.csv", index=False)
print("\nPredictions saved to predictions.csv")


C:\Users\vidus\AppData\Local\Programs\Python\Python312\Lib\site-packages\torchvision\models\_utils.py:208: UserWarning: The parameter 'pretrained' is deprecated since 0.13 and may be removed in the future, please use 'weights' instead.
  warnings.warn(
C:\Users\vidus\AppData\Local\Programs\Python\Python312\Lib\site-packages\torchvision\models\_utils.py:223: UserWarning: Arguments other than a weight enum or `None` for 'weights' are deprecated since 0.13 and may be removed in the future. The current behavior is equivalent to passing `weights=None`.
  warnings.warn(msg)



Missing Files from 'test' Folder:
['filename']


Processing images: 100%|██████████████████████████████████████████████████████████| 555/555 [00:19<00:00, 28.09image/s]


Model Accuracy: 97.83%

Confusion Matrix:
[[286   3   1   0   0]
 [  2  72   0   1   0]
 [  1   0 139   2   1]
 [  0   0   0  42   0]
 [  1   0   0   0   3]]

Predictions saved to predictions.csv


In [2]:
import pandas as pd


df = pd.read_csv("predictions.csv")


matching_predictions = df[df["actual_label"] == df["predicted_label"]]


matching_predictions.to_csv("matching_predictions.csv", index=False)

print("Matching predictions saved to matching_predictions.csv")

Matching predictions saved to matching_predictions.csv
